services:
  redpanda1:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.6
    container_name: redpanda1
    command:
      - redpanda
      - start
      - --node-id 1
      - --overprovisioned
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda1:9092,OUTSIDE://localhost:19092
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr redpanda1:33145
    ports:
      - 19092:19092 # Kafka API port
      - 18081:8081  # Schema registry port
      - 19644:9644  # Admin and metrics
  console:
    image: docker.redpanda.com/redpandadata/console:v2.3.1
    container_name: redpanda-console
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        redpanda:
          adminApi:
            enabled: true
            urls:
              - "http://redpanda1:9644"
        kafka:
          brokers:
            - "redpanda1:9092"
          schemaRegistry:
            enabled: true
            urls:
              - "http://redpanda1:8081"
          protobuf:
            enabled: true
            schemaRegistry:
              enabled: true
              refreshInterval: 1m
    ports:
      - 8080:8080
    depends_on:
      - redpanda1
